function [value,isterminal,direction] = Event_TD_matlabFunction(t,in2)
%Event_TD_matlabFunction
%    [VALUE,ISTERMINAL,DIRECTION] = Event_TD_matlabFunction(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Jul-2022 17:13:08

y1 = in2(1,:);
value = y1;
if nargout > 1
    isterminal = 1.0;
end
if nargout > 2
    direction = -1.0;
end
